### ISSUE TITLE
False Positives

### ISSUE THREAD

**Issue by aileron565** [brianspilner01/media-server-scripts#14]
I think I've found a false positive with [Line 29](https://github.com/brianspilner01/media-server-scripts/blob/master/sub-clean.sh#L29) particularly the `|[^a-z]www\.|` segment. It will also catch the words Ewww. and Awww. Updating that segment to `|[^A-Za-z]www\.|` should resolve these few instances. Also, thank you for the work you put into making this. I was about to make it myself but then found yours.

**Comment by brianspilner01** [comment]
That won't fix those cases unfortunately, if you look closer at the awk command you'll notice it only checks against an all lowercase version of each block (and would still match those cases anyway). There will always be some trade-off with occasional false positives, hence I encourage people to modify the script as they see fit for themselves. Personally I think taking out those additional web URLs offsets the rare chance of an "awww. or ewww." specifically. By all means remove that from your own script though!
