### ISSUE TITLE
Script clipping the letter R from lines

### ISSUE THREAD

**Issue by ambilzi** [brianspilner01/media-server-scripts#15]
I have installed the sub-clean.sh script to run as a post-processing script in Bazarr according to the instructions in the script comments.

It's running on a macOS System running 10.13.

I've noticed that on many subtitles, the letter "r" is stripped from the end of some words.

I have not been able to identify any consistency as to why. It happens in a small percentage of cases that fit this criteria (5% maybe?)

A simple example:

3
00:01:19,162 --> 00:01:21,538
deer

the word "deer" is truncated to "dee"

**Comment by brianspilner01** [comment]
I've made a change that will hopefully fix this problem, seems to be an issue with older versions of sed from what I can see. Please let me know if it works for you!

**Comment by ambilzi** [comment]
I tested it again in the example I provided with the new script. Appears to be resolved. I'll certainly let you know if I see it come up again.
Thanks for the quick fix!
