### ISSUE TITLE
Suggestion: Ask for user input

### ISSUE THREAD

**Issue by scda360** [brianspilner01/media-server-scripts#5]
Hey Brian,

I really like Sub-clean.sh, however it sometimes removes too much lines

Is it possible to add an option to ask for the user input/interations before deleting the line?

Ex:
The following line matches the Regex Search:
"lorem ipsum ..... "
Would you like to remove it? Y/N

**Comment by brianspilner01** [comment]
I added a separate script for you (sub-clean-interactive.sh), as modifying the current one would make automating the script more difficult. In the future these could possibly be merged perhaps with a flag such as --interactive but I think given the scope, this will suffice.
