### ISSUE TITLE
Breaks in Bazarr with paths that contain single-quotes

### ISSUE THREAD

**Issue by deepfriedmind** [brianspilner01/media-server-scripts#6]
If you add it to Bazarr as you've outlined here:

https://github.com/brianspilner01/media-server-scripts/blob/e9a6145d6f765a42d4fced52078524d8e6b2ae0f/sub-clean.sh#L10-L11

It will break if the path contains a single-quote. If you add it with double quotes, i.e. `"{{subtitles}}"`,  it works.

**Comment by Brando47** [comment]
Good pick, thanks!

**Comment by deepfriedmind** [comment]
Oh, and **huge** thanks for the script btw :)

**Comment by brianspilner01** [comment]
You're very welcome, thanks!
