### ISSUE TITLE
Bazarr picks mkv file instead of srt

### ISSUE THREAD

**Issue by Shawn9347** [brianspilner01/media-server-scripts#9]
Hello,

I have been using your script for two months and I really liked it untill I pulled the updated version. I am using your sub-clean.sh with bazarr v 0.9.3 but it's not working. 

I am getting this error message every time bazarr downloads a subtitle. 

"BAZARR Post-processing result for file /data/Movies/The Magnificent Seven (2016)/The Magnificent Seven (2016).mkv : Provided file must be .srt"

For some reason it's picking the mkv file instead of the srt file. I haven't modified the script. I just put the line "/config/sub-clean.sh "{{subtitles}}" --" in custom processing in bazarr. 

Any idea what I'm doing wrong or maybe the script isn't compatible with bazarr v 0.9.3? That version came out on the 25th on march.

Thanks in advance

![process](https://user-images.githubusercontent.com/48714886/112715871-4027c280-8ee3-11eb-9225-f40c71ab2ddb.png)

**Comment by brianspilner01** [comment]
I'm running the latest development release of bazarr using docker (0.9.4-beta8) and can't seem to replicate this issue. I did try with 0.9.3 but I don't think my instance likes being reverted to an old version and refuses to download anything at all so I can't test that sorry, although I can't imagine it would affect this. Perhaps try updating your sub-clean.sh script from here? I have recently made some small changes to the line that checks if the sub is a .srt file.

Failing that, you could try debug by setting your post-processing command to `echo "{{subtitles}}" --` and check your logs that bazarr is correctly substituting "{{subtitles}}" with the path of the downloaded srt files.

**Comment by Shawn9347** [comment]
It works again. I pull your new new script xD. from a few hours ago and now it's working. Thank youuuu

**Comment by brianspilner01** [comment]
No worries mate!
